server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 50MB

# nơi lưu file upload (được mount volume vào)
app:
  upload:
    dir: ${APP_UPLOAD_DIR:/opt/uploads}
