spring:
  application:
    name: e-commerce-services
  main:
    banner-mode: "off"
  profiles:
    active:
      - local
  datasource:
    url: jdbc:postgresql://localhost:5432/services_db
    username: postgres
    password: Naul126@/
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration/postgres
    baseline-on-migrate: true
    clean-disabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
server:
  port: 8080
app:
  jwt:
    secret: "sagjfagslakgnwijeinkfdnglkgnaoewiethergndlfngbadlfgnasngldagughdlanfgkdnghsldnfherghdlgndfnhsldfhnsldfhnalqjsgog"
    access-exp-minutes: 15
    refresh-exp-days: 14
  upload:
    dir: ${user.home}/ecommerce-uploads
